/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aed.view;

import com.aed.view.Additions;
import com.aed.view.Register;
import com.aed.exceptions.CustomException;
import com.aed.model.Community;
import com.aed.model.Person;
import java.awt.Color;
import java.awt.Image;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author yashpawar
 */
public class LoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginJFrame
     */
    String userImage = "./uploads/profileImage/username.png";
    String passImage = "./uploads/profileImage/pass.png";
    int trycatch = 0;
    public static Person loggedInPerson;

    public LoginJFrame(int flag) {
        
        if(flag == 0){
     Additions.communityMap.put(Additions.communityId, new Community(Additions.communityId++,"Alphonsus St", "Boston","02120"));
     Additions.communityMap.put(Additions.communityId, new Community(Additions.communityId++,"Huntington Ave", "Boston","02122"));
     Additions.communityMap.put(Additions.communityId, new Community(Additions.communityId++,"Rivery", "New York","02123"));
     
     //Person Data Addition
     Additions.personMap.put(Additions.personId, new Person(Additions.personId, "Chakradhar",Integer.toString(Additions.personId++),"1234","SA",23,"Male","xyz",75,"Boston",100));  
     Additions.personMap.put(Additions.personId, new Person(Additions.personId, "Rakshit",Integer.toString(Additions.personId++),"1234","CA",25,"Male","xyz",75,"Boston",101));     
     Additions.personMap.put(Additions.personId, new Person(Additions.personId, "Palak",Integer.toString(Additions.personId++),"1234","CA",21,"Female","xyz",881,"Boston",100));    
     Additions.personMap.put(Additions.personId, new Person(Additions.personId, "Manthan",Integer.toString(Additions.personId++),"1234","Person",21,"Male","xyz",882,"Boston",101));    
     Additions.personMap.put(Additions.personId, new Person(Additions.personId, "Yash",Integer.toString(Additions.personId++),"1234","Person",21,"Male","xyz",883,"Boston",101)); 
     Additions.personMap.put(Additions.personId, new Person(Additions.personId, "Gaurang",Integer.toString(Additions.personId++),"1234","Person",25,"Male","xyz",75,"Boston",100)); 
        initComponents();
        loggedInPerson = null;
        signInButton.setForeground(Color.white);
        userImgLabel.setIcon(new ImageIcon(new ImageIcon(userImage).getImage().getScaledInstance(userImgLabel.getWidth(), userImgLabel.getHeight(), Image.SCALE_SMOOTH)));
        passImgLabel.setIcon(new ImageIcon(new ImageIcon(passImage).getImage().getScaledInstance(passImgLabel.getWidth(), passImgLabel.getHeight(), Image.SCALE_SMOOTH)));
    }
    else{
       initComponents();
        loggedInPerson = null;
        signInButton.setForeground(Color.white);
        userImgLabel.setIcon(new ImageIcon(new ImageIcon(userImage).getImage().getScaledInstance(userImgLabel.getWidth(), userImgLabel.getHeight(), Image.SCALE_SMOOTH)));
        
        passImgLabel.setIcon(new ImageIcon(new ImageIcon(passImage).getImage().getScaledInstance(passImgLabel.getWidth(), passImgLabel.getHeight(), Image.SCALE_SMOOTH)));
 

    }
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameField = new javax.swing.JTextField();
        signInButton = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();
        userImgLabel = new javax.swing.JLabel();
        passImgLabel = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        photo = new javax.swing.JLabel();
        signInButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1314, 1499));

        signInButton.setText("Login");
        signInButton.setToolTipText("");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        loginLabel.setFont(new java.awt.Font("Kokonor", 3, 30)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginLabel.setText("   Login");

        passImgLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passImgLabelMouseClicked(evt);
            }
        });

        signInButton1.setForeground(new java.awt.Color(204, 204, 204));
        signInButton1.setText("Signup");
        signInButton1.setToolTipText("");
        signInButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userImgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(passImgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(photo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(userNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(signInButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signInButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String loginAction() throws CustomException {

        for (Person set : Additions.personMap.values()) {
            if (set.getUserName().equals(userNameField.getText())) {
                try {
                    if (set.getPassword().equals(passField.getText())) {
                        
                        Additions.sysid = set.getPersonID();
                        //System.err.println("in login function"+set.getPersonID());
                        return set.getRole();
                    } else {
                        throw new CustomException("Incorrect Password");
                    }
                } catch (CustomException e) {
                    JOptionPane.showMessageDialog(this, "Incorrect Username Password Combination");
                    userNameField.setText("");
                    passField.setText("");
                    break;
                }
            }
        }
        return "";
    }
    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        if (userNameField.getText().isEmpty() && passField.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Please Enter UserName Password");
        else {
            try {
                if (loginAction().equals("SA")) {
 
                    Additions.role="SA";
                    new Additions().show();
                    dispose();
                } else if (loginAction().equals("HA")) {
                    Additions.role="HA";
                    new Additions().show();
                    dispose();
                } else if (loginAction().equals("CA")) {
                    Additions.role="CA";
                    new Additions().show();

                    dispose();
                } else if (loginAction().equals("Person")) {
                    Additions.role="Person";
                    new Additions().show();
                    dispose();
                } else if (loginAction().equals("Doctor")) {
                    Additions.role="Doctor";
                    new Additions().show();

                    dispose();
                }
            } catch (CustomException ex) {
                Logger.getLogger(LoginJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_signInButtonActionPerformed

    private void passImgLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passImgLabelMouseClicked
        // TODO add your handling code here:
        if(trycatch==0){
            passField.setEchoChar((char)0);
            trycatch=1;
        }
        else{
            passField.setEchoChar('*');
            trycatch=0;
        }
    }//GEN-LAST:event_passImgLabelMouseClicked

    private void signInButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButton1ActionPerformed
        // TODO add your handling code here:
        new Register().show();
        dispose();
    }//GEN-LAST:event_signInButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passImgLabel;
    private javax.swing.JLabel photo;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton signInButton1;
    private javax.swing.JLabel userImgLabel;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
